# Generated by Django 3.1.4 on 2020-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(unique=True)),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
