# Generated by Django 3.1.4 on 2020-12-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201210_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='onVisit',
        ),
    ]
